name: Publish and release cumulusci-plus-azure-devops

on:
  push:
    branches:
      - main
    paths:
      - cumulusci_ado/__about__.py

concurrency: publishing

jobs:
  publish-to-pypi:
    name: Publish new release to PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install build tools
        run: pip install hatch
      - name: Build package
        run: hatch build -c
      - name: Publish to PyPI
        env:
          HATCH_INDEX_USER: "__token__"
          HATCH_INDEX_AUTH: ${{ secrets.TEST_PYPI_TOKEN }}
        run: hatch publish --repo https://test.pypi.org/legacy/
